version: 0.2

phases:
  
  build:
    commands:
     - nuget restore
     - msbuild .\WebApplicationSample\WebApplicationSample.csproj /t:Package /p:DeployIisAppPath="Default Web Site"
  post_build:
    commands:
     - mkdir OutputPackage
     - PowerShell Expand-Archive .\WebApplicationSample\obj\Debug\Package\WebApplicationSample.zip -DestinationPath .\OutputPackage
artifacts:
  files:
   - '**/*'
  base-directory: '.\OutputPackage'
